# Generated by Django 4.0.5 on 2022-07-28 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
